### ISSUE TITLE
[Chore] Implement tests for the scraper

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-script#3]
## Issue

Automated tests do not cover the core business logic of scraping of the Google search page.

## Expected

While 100% test coverage is not required for this code challenge, all critical paths of the application should be unit-tested. The scraping, the core business logic, must receive the most attention. There are also some challenges to writing such automated tests, hence it is an expected component of an applicant's submission.

**Comment by Prabeshpd** [comment]
I have added the test for the scraper service.  For the test axios request has been mocked so that cheerio can parse the mocked file and test whether the scraper function works properly or not.

**Comment by olivierobert** [comment]
Good effort on adding these tests 👍
