### ISSUE TITLE
[Chore] Extract hard-coded DOM selectors

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-script#4]
## Issue

Scraping the Google search page requires selecting specific DOM elements by class names. Google routinely changes these (we,, to avoid scrapers like us 😉 ). However, the selectors are hard-coded, making the code hard to change:

https://github.com/Prabeshpd/web-scraper-script/blob/a7d306fd901bf2a30924dd14d68f14d36fcf85e9/src/services/scraper.ts#L32-L42

## Expected

Refactor hard-coded values into configurable/changeable variables.

**Comment by Prabeshpd** [comment]
I have extracted out the hard coded dom selectors here and placed them in config from where we can control through env variables as application loads.
